owner: Cosmos-Factory-Island
repo: huertobio-status

site-name: HuertoBio Status

status-website:
  cname: status.huerto.bio
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HuertoBio Status
  introTitle: "Página de estado de los servicios de HuertoBio."
  introMessage: "Monitorización en tiempo real de los servicios y APIs."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Cosmos-Factory-Island/huertobio-status

sites:
  - name: App HuertoBio
    url: https://beta.huerto.bio
  - name: API Backend
    url: https://api.huerto.bio/api/health
